/**
 * planetsData.js
 * Részletes, tudományosan pontos és érdekes magyar nyelvű adatbázis a Naprendszer égitestjeiről.
 */

export const solarSystemData = [
  {
    id: "sun",
    name: "Nap",
    latinName: "Sol",
    type: "Csillag (Sárga törpe, G2V)",
    tagline: "A Naprendszer gravitációs és energetikai szíve",
    color: "#ffaa00",
    glowColor: "rgba(255, 170, 0, 0.6)",
    diameterKm: "1 392 700 km",
    diameterEarthRatio: "109× a Föld átmérője",
    distanceFromSunKm: "0 km",
    distanceFromSunAU: "0 CsE",
    orbitalPeriod: "– (A Galaxis magja körül: ~230 millió év)",
    rotationPeriod: "25 - 35 nap (differenciális forgás)",
    temperature: "Mag: ~15 000 000 °C | Felszín: ~5 500 °C",
    moonsCount: 0,
    massRatio: "A Naprendszer teljes tömegének 99,86%-a",
    overview: "A Nap a Naprendszer központi csillaga, egy G2V színképtípusú sárga törpe. Hatalmas tömege tartja pályáján az összes bolygót, törpebolygót, üstököst és aszteroidát. Belsejében másodpercenként mintegy 600 millió tonna hidrogén alakul héliummá fúzió révén, ami a földi élethez szükséges fényt és meleget biztosítja.",
    facts: [
      "A Nap tömege mintegy 333 000-szerese a Földének, és belsejében körülbelül 1,3 millió Föld férne el.",
      "A napfénynek pontosan 8 perc és 20 másodperc szükséges ahhoz, hogy elérje a Föld felszínét.",
      "A napfelszínen gyakoriak a napfoltok és a gigantikus fler-kitörések, melyek a földi sarki fényt és geomágneses viharokat okozzák.",
      "Körülbelül 4,6 milliárd éves, és még nagyjából 5 milliárd évig biztosítja a stabil energiatermelést, mielőtt vörös óriássá duzzadna."
    ],
    size3D: 14.0,
    orbitRadius3D: 0,
    orbitSpeed: 0,
    rotationSpeed: 0.002,
    texture: "sun"
  },
  {
    id: "mercury",
    name: "Merkúr",
    latinName: "Mercurius",
    type: "Kőzetbolygó",
    tagline: "A Naptól legközelebbi, forró és fagyos világ",
    color: "#a8a8a8",
    glowColor: "rgba(180, 180, 180, 0.5)",
    diameterKm: "4 879 km",
    diameterEarthRatio: "0,38× a Föld átmérője",
    distanceFromSunKm: "57,9 millió km",
    distanceFromSunAU: "0,387 CsE",
    orbitalPeriod: "88 földi nap",
    rotationPeriod: "58,6 földi nap",
    temperature: "Nappal: +430 °C | Éjszaka: -180 °C",
    moonsCount: 0,
    massRatio: "0,055 Föld-tömeg",
    overview: "A Merkúr a legkisebb bolygó és a legközelebb kering a Naphoz. Mivel gyakorlatilag nincs érdemi légköre, nem képes megtartani a hőt, így a Naprendszer egyik legszélsőségesebb hőingadozású égiteste. Felszínét sűrű krátermezők borítják, megjelenése a Holdéhoz nagyon hasonló.",
    facts: [
      "Bár a Naphoz legközelebbi bolygó, mégsem a legforróbb; a Vénusz vastag üvegházhatású légköre miatt még nála is melegebb.",
      "A Merkúr pólusközeli mély krátereiben, ahová sosem süt be a Nap, a radaros mérések szerint fagyott vízjég rejtőzik.",
      "A Naprendszer leggyorsabb bolygója: megközelítőleg 47 km/s sebességgel száguld a pályáján.",
      "Óriási fémmaggal rendelkezik, amely a bolygó teljes térfogatának több mint 60%-át teszi ki."
    ],
    size3D: 1.8,
    orbitRadius3D: 28,
    orbitSpeed: 0.04,
    rotationSpeed: 0.008,
    texture: "mercury"
  },
  {
    id: "venus",
    name: "Vénusz",
    latinName: "Venus",
    type: "Kőzetbolygó",
    tagline: "A pokoli ikertestvér: vastag felhők és tomboló üvegházhatás",
    color: "#e3bb76",
    glowColor: "rgba(227, 187, 118, 0.5)",
    diameterKm: "12 104 km",
    diameterEarthRatio: "0,95× a Föld átmérője",
    distanceFromSunKm: "108,2 millió km",
    distanceFromSunAU: "0,723 CsE",
    orbitalPeriod: "224,7 földi nap",
    rotationPeriod: "243 földi nap (retrográd / visszafelé forog!)",
    temperature: "Átlagosan: ~465 °C (állandó éjjel-nappal)",
    moonsCount: 0,
    massRatio: "0,815 Föld-tömeg",
    overview: "Méretét és tömegét tekintve a Föld ikertestvérének is nevezik, ám felszíni körülményei valóságos poklot idéznek. Sűrű szén-dioxid légköre és kénsavfelhői féktelen üvegházhatást hoznak létre, a felszíni légnyomás pedig 92-szerese a földinek – megegyezik a földi óceánok 900 méteres mélységében tapasztalható nyomással.",
    facts: [
      "A Naprendszer legforróbb bolygója: a 465 °C-os felszíni hőmérsékleten az ólom és a cink is megolvad.",
      "A Vénuszon egy nap hosszabb, mint egy év! 243 földi napig tart egyetlen tengelyforgása, miközben 225 nap alatt kerüli meg a Napot.",
      "A legtöbb bolygóval ellentétben a Vénusz az óramutató járásával megegyező irányban forog (retrográd forgás), így nála a Nap nyugaton kel és keleten nyugszik.",
      "Az éjszakai égbolt legfényesebb csillagszerű pontja, a népi nyelvben 'Esthajnalcsillagként' ismert."
    ],
    size3D: 3.2,
    orbitRadius3D: 42,
    orbitSpeed: 0.025,
    rotationSpeed: -0.004,
    texture: "venus"
  },
  {
    id: "earth",
    name: "Föld",
    latinName: "Terra",
    type: "Kőzetbolygó (Élő világ)",
    tagline: "Kék oázis az űrben – az egyetlen ismert égitest élettel",
    color: "#2a75d3",
    glowColor: "rgba(42, 117, 211, 0.6)",
    diameterKm: "12 742 km",
    diameterEarthRatio: "1,0× (Bázisérték)",
    distanceFromSunKm: "149,6 millió km",
    distanceFromSunAU: "1,000 CsE",
    orbitalPeriod: "365,25 nap",
    rotationPeriod: "23 óra 56 perc 4 másodperc",
    temperature: "Átlagosan: +15 °C (Rekordok: -89 °C és +57 °C)",
    moonsCount: 1,
    massRatio: "5,97 × 10²⁴ kg",
    overview: "A Naprendszer ötödik legnagyobb bolygója, és jelenleg az egyetlen hely a világegyetemben, ahol bizonyítottan kialakult és fennmaradt az élet. Felszínének több mint 70%-át folyékony víz borítja. Erős mágneses mezője és nitrogén-oxigén légköre megvédi a bioszférát a káros kozmikus sugárzástól.",
    facts: [
      "A Föld a legsűrűbb bolygó az egész Naprendszerben (5,51 g/cm³), köszönhetően a hatalmas nikkel-vas magnak.",
      "Hűséges kísérője a Hold, amely stabilizálja a bolygó 23,4 fokos tengelyferdeségét, lehetővé téve a kiegyensúlyozott évszakok létezését.",
      "A légkör kék színét a Rayleigh-szóródás adja: a levegő molekulái a kék fényt sokkal erősebben szórják, mint a vöröset.",
      "A Föld nem tökéletes gömb, hanem forgási ellipszoid: az Egyenlítőnél a centrifugális erő miatt kissé kidudorodik."
    ],
    size3D: 3.4,
    orbitRadius3D: 60,
    orbitSpeed: 0.018,
    rotationSpeed: 0.01,
    texture: "earth"
  },
  {
    id: "mars",
    name: "Mars",
    latinName: "Mars",
    type: "Kőzetbolygó",
    tagline: "A Vörös Bolygó – a Naprendszer legnagyobb vulkánjának és kanyonjának otthona",
    color: "#d14b28",
    glowColor: "rgba(209, 75, 40, 0.6)",
    diameterKm: "6 779 km",
    diameterEarthRatio: "0,53× a Föld átmérője",
    distanceFromSunKm: "227,9 millió km",
    distanceFromSunAU: "1,524 CsE",
    orbitalPeriod: "687 földi nap (~1,88 év)",
    rotationPeriod: "24 óra 37 perc (nagyon hasonlít a földi naphoz)",
    temperature: "Átlagosan: -63 °C (Nyáron az egyenlítőnél: +20 °C, télen a sarkokon: -140 °C)",
    moonsCount: 2,
    massRatio: "0,107 Föld-tömeg",
    overview: "A Mars vöröses színét a felszíni porban lévő magas vas-oxid (rozsda) koncentrációnak köszöni. Ritka szén-dioxid légköre ellenére ma is aktív időjárással bír: hatalmas, bolygóméretű porviharok söpörnek végig rajta. A jövőbeli emberi űrutazás és kolonizáció első számú célpontja.",
    facts: [
      "Itt található az Olympus Mons, a Naprendszer legmagasabb hegye és kialudt vulkánja, amely 22 km magasra tör – csaknem háromszorosa a Mount Everestnek!",
      "A Valles Marineris kanyonrendszer több mint 4 000 km hosszú és néhol 7 km mély; simán átszelné Észak-Amerikát.",
      "Két apró, krumpli alakú holdja van, a Phobos és a Deimos, amelyek valószínűleg befogott aszteroidák.",
      "A kutatószondák bizonyították, hogy a távoli múltban folyékony víz, folyók és tavak szabdalhatták a Mars felszínét."
    ],
    size3D: 2.3,
    orbitRadius3D: 78,
    orbitSpeed: 0.014,
    rotationSpeed: 0.009,
    texture: "mars"
  },
  {
    id: "jupiter",
    name: "Jupiter",
    latinName: "Iuppiter",
    type: "Gázóriás",
    tagline: "A bolygók királya – a Naprendszer védelmező óriása",
    color: "#d9a066",
    glowColor: "rgba(217, 160, 102, 0.6)",
    diameterKm: "139 820 km",
    diameterEarthRatio: "11,0× a Föld átmérője",
    distanceFromSunKm: "778,5 millió km",
    distanceFromSunAU: "5,203 CsE",
    orbitalPeriod: "11,86 földi év",
    rotationPeriod: "9 óra 55 perc (a leggyorsabban forgó bolygó)",
    temperature: "Felhőtetőn: -110 °C | Magban: ~24 000 °C",
    moonsCount: 95,
    massRatio: "318 Föld-tömeg (a többi bolygó együttes tömegének 2,5-szerese)",
    overview: "A Jupiter a Naprendszer vitathatatlan óriása. Főként hidrogénből és héliumból áll, szilárd felszíne nincs. Hatalmas gravitációjával porszívóként téríti el vagy fogja be az üstökösöket és aszteroidákat, ezáltal óriási védelmet nyújt a belső kőzetbolygóknak, így a Földnek is.",
    facts: [
      "A híres Nagy Vörös Folt egy olyan gigantikus anticiklonális vihar, amely már legalább 350 éve tombol, és akkora, hogy az egész Föld elférne benne.",
      "Bár óriási a mérete, a Jupiter forog a leggyorsabban: egyetlen nap mindössze alig 10 óráig tart rajta.",
      "Négy legnagyobb kísérője a Galilei-holdak: az Io (vulkánok világa), az Europa (jégpáncél alatti óceán), a Ganymedes (a Naprendszer legnagyobb holdja, nagyobb a Merkúrnál!) és a Callisto.",
      "Ha a Jupiter tömege a keletkezésekor mintegy 80-szorosa lett volna, csillaggá vált volna, és egy kettőscsillag-rendszerben élnénk."
    ],
    size3D: 6.8,
    orbitRadius3D: 105,
    orbitSpeed: 0.008,
    rotationSpeed: 0.02,
    texture: "jupiter"
  },
  {
    id: "saturn",
    name: "Szaturnusz",
    latinName: "Saturnus",
    type: "Gázóriás",
    tagline: "A gyűrűk ura – a Naprendszer leglátványosabb égiteste",
    color: "#e2bf7d",
    glowColor: "rgba(226, 191, 125, 0.6)",
    diameterKm: "116 460 km",
    diameterEarthRatio: "9,1× a Föld átmérője",
    distanceFromSunKm: "1,43 milliárd km",
    distanceFromSunAU: "9,539 CsE",
    orbitalPeriod: "29,45 földi év",
    rotationPeriod: "10 óra 33 perc",
    temperature: "Felhőtetőn: -140 °C",
    moonsCount: 146,
    massRatio: "95 Föld-tömeg",
    overview: "A Szaturnusz leginkább lélegzetelállító és komplex gyűrűrendszeréről ismert, amely túlnyomórészt milliárdnyi vízjég-részecskéből, kőzetdarabból és űrporból áll. Bár a második legnagyobb bolygó, sűrűsége kisebb a vízénél: egy képzeletbeli óriási kádban lebegne a víz felszínén.",
    facts: [
      "A gyűrűk átmérője eléri a 282 000 kilométert, vastagságuk viszont rendkívül csekély, helyenként mindössze 10 és 100 méter közötti!",
      "A legtöbb felfedezett holddal rendelkezik: jelenleg 146 hivatalosan elismert kísérője van.",
      "Legnagyobb holdja, a Titán az egyetlen olyan hold a Naprendszerben, amelynek sűrű légköre van, felszínén pedig folyékony metán- és etántavak találhatók.",
      "Az északi pólusán egy különös, gigantikus, hatezerszög alakú (hexagon) viharrendszer forog."
    ],
    size3D: 5.6,
    orbitRadius3D: 135,
    orbitSpeed: 0.006,
    rotationSpeed: 0.018,
    hasRings: true,
    ringInnerRadius: 7.0,
    ringOuterRadius: 13.0,
    texture: "saturn"
  },
  {
    id: "uranus",
    name: "Uránusz",
    latinName: "Uranus",
    type: "Jégóriás",
    tagline: "Az oldalán guruló jeges titán",
    color: "#68d8d6",
    glowColor: "rgba(104, 216, 214, 0.6)",
    diameterKm: "50 724 km",
    diameterEarthRatio: "4,0× a Föld átmérője",
    distanceFromSunKm: "2,87 milliárd km",
    distanceFromSunAU: "19,19 CsE",
    orbitalPeriod: "84 földi év",
    rotationPeriod: "17 óra 14 perc (retrográd)",
    temperature: "Átlagosan: -195 °C | Mért rekord: -224 °C (a leghidegebb bolygó)",
    moonsCount: 28,
    massRatio: "14,5 Föld-tömeg",
    overview: "Az Uránusz az első bolygó, amelyet modern távcsővel fedeztek fel (William Herschel, 1781). Jégóriásként atmoszférája és köpenye fagyott vízből, ammóniából és metánból tevődik össze. A metángáz elnyeli a vörös fényt, ez adja az Uránusz jellegzetes, ragyogó akvamarin-ciánkék színét.",
    facts: [
      "Tengelyferdesége eléri a 98 fokot, ami azt jelenti, hogy gyakorlatilag az oldalára dőlve kering a Nap körül, mintha gurulna a pályáján.",
      "Az extrém dőlésszög miatt a pólusokon 42 évig folyamatos nappal, majd 42 évig tartó sötét sarki éjszaka uralkodik.",
      "Bár a Neptunusz távolabb van a Naptól, az Uránusz rendelkezik a Naprendszer leghidegebb mért légkörével (-224 °C).",
      "Az Uránusznak is van 13 halvány, sötét gyűrűje, és 28 ismert holdja, melyeket Shakespeare és Alexander Pope műveinek szereplőiről neveztek el."
    ],
    size3D: 4.2,
    orbitRadius3D: 165,
    orbitSpeed: 0.004,
    rotationSpeed: -0.012,
    texture: "uranus"
  },
  {
    id: "neptune",
    name: "Neptunusz",
    latinName: "Neptunus",
    type: "Jégóriás",
    tagline: "A szuperszonikus viharok mélykék birodalma",
    color: "#3867d6",
    glowColor: "rgba(56, 103, 214, 0.6)",
    diameterKm: "49 244 km",
    diameterEarthRatio: "3,88× a Föld átmérője",
    distanceFromSunKm: "4,50 milliárd km",
    distanceFromSunAU: "30,07 CsE",
    orbitalPeriod: "164,8 földi év",
    rotationPeriod: "16 óra 6 perc",
    temperature: "Átlagosan: -200 °C",
    moonsCount: 16,
    massRatio: "17,1 Föld-tömeg",
    overview: "A Naprendszer legkülső ismert nagybolygója. Matematikai számítások alapján találták meg 1846-ban, mivel az Uránusz pályájában észlelt eltérésekből megjósolták a helyét. Élénk kobaltkék színű atmoszférájában a Naprendszer leggyorsabb és legerőszakosabb szelei süvítenek.",
    facts: [
      "A Neptunusz szeleinek sebessége elérheti a döbbenetes 2 100 km/órát, ami a hangsebesség csaknem kétszerese!",
      "Felfedezése óta (1846) mindössze egyetlen teljes kört tett meg a Nap körül, ezt 2011-ben fejezte be.",
      "Fő holdja a fagyott Triton, amely retrográd pályán kering, és nitrogén-gejzírek lövellnek ki a felszínéből.",
      "A Naptól olyan messze van, hogy a déli verőfényes délben is olyan halvány ott a Nap fénye, mint nálunk a Földön egy sötétebb alkonyat idején."
    ],
    size3D: 4.0,
    orbitRadius3D: 195,
    orbitSpeed: 0.003,
    rotationSpeed: 0.014,
    texture: "neptune"
  },
  {
    id: "pluto",
    name: "Plútó",
    latinName: "Pluto",
    type: "Törpebolygó (Kuiper-övi égitest)",
    tagline: "A fagyos szívű törpebolygó a Naprendszer peremén",
    color: "#bfa38a",
    glowColor: "rgba(191, 163, 138, 0.5)",
    diameterKm: "2 376 km",
    diameterEarthRatio: "0,18× a Föld átmérője",
    distanceFromSunKm: "5,91 milliárd km",
    distanceFromSunAU: "39,48 CsE",
    orbitalPeriod: "248 földi év",
    rotationPeriod: "6,39 földi nap",
    temperature: "Átlagosan: -230 °C",
    moonsCount: 5,
    massRatio: "0,002 Föld-tömeg",
    overview: "A Plútót 1930-as felfedezésétől 2006-ig a kilencedik bolygóként tartották számon, amikor is a Nemzetközi Csillagászati Unió átsorolta a törpebolygók kategóriájába. A New Horizons űrszonda 2015-ös elrepülése meglepően dinamikus, hegyekkel és jégmezőkkel teli világot tárt fel.",
    facts: [
      "Felszínén egy hatalmas, szív alakú fagyott nitrogénsíkság látható, amelyet Tombaugh Regio-nak neveznek.",
      "Keringési pályája annyira elnyúlt és megdőlt, hogy időnként (legutóbb 1979 és 1999 között) közelebb volt a Naphoz, mint a Neptunusz.",
      "Kísérője, a Charon olyan nagy hozzá képest, hogy kettős törpebolygó-rendszert alkotnak, közös tömegközéppontjuk a Plútón kívül található.",
      "Kisebb, mint a Föld Holdja, sőt még az Egyesült Államok szélességénél is keskenyebb!"
    ],
    size3D: 1.2,
    orbitRadius3D: 220,
    orbitSpeed: 0.002,
    rotationSpeed: 0.004,
    texture: "pluto"
  }
];
